#pragma once

#include <gtest/gtest.h>
#include <memory>
#include <string>

#if defined(_WIN32)
#include <process.h>  // for _getpid()
#else
#include <unistd.h>   // for getpid()
#endif

#include "fbpp/core/connection.hpp"
#include "fbpp/core/transaction.hpp"
#include "fbpp/core/exception.hpp"
#include "fbpp_util/connection_helper.hpp"

namespace fbpp {
namespace test {

using namespace fbpp::core;

// Base class for all fbpp tests
class FbppTestBase : public ::testing::Test {
protected:
    // Legacy method - kept for compatibility, but use fbpp::util::getConnectionParams() directly
    static void initLoggingFromConfig(const fbpp::util::json&) {
        // Logging subsystem removed; trace observer can be configured separately.
    }
};

// Test with persistent database (created once, reused across tests)
class PersistentDatabaseTest : public FbppTestBase {
protected:
    static void SetUpTestSuite() {
        // Use connection helper to get params with ENV overrides
        db_params_ = fbpp::util::getConnectionParams("tests.persistent_db");

        // Create database if it doesn't exist
        bool db_existed = Connection::databaseExists(db_params_.database, db_params_);
        if (!db_existed) {
            Connection::createDatabase(db_params_);
        }

        // Connect to database
        auto conn = std::make_unique<Connection>(db_params_);

        // Try to create tables (will fail silently if they already exist)
        try {
            conn->ExecuteDDL(
                "CREATE TABLE test_data ("
                "    id INTEGER NOT NULL PRIMARY KEY,"
                "    name VARCHAR(100),"
                "    amount DOUBLE PRECISION,"
                "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                ")");
        } catch (...) {
            // Table already exists, ignore
        }

        try {
            conn->ExecuteDDL(
                "CREATE TABLE test_log ("
                "    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                "    message VARCHAR(500),"
                "    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                ")");
        } catch (...) {
            // Table already exists, ignore
        }

        // Create TABLE_TEST_1 for extended types testing
        try {
            conn->ExecuteDDL(
                "CREATE TABLE TABLE_TEST_1 ("
                "    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                "    F_BIGINT            BIGINT,"
                "    F_BOOLEAN           BOOLEAN,"
                "    F_CHAR              CHAR(10),"
                "    F_DATE              DATE,"
                "    F_DECFLOAT          DECFLOAT(34),"
                "    F_DECIMAL           DECIMAL(34,8),"
                "    F_DOUBLE_PRECISION  DOUBLE PRECISION,"
                "    F_FLOAT             FLOAT,"
                "    F_INT128            INT128,"
                "    F_INTEGER           INTEGER UNIQUE,"
                "    F_NUMERIC           NUMERIC(16,6),"
                "    F_SMALINT           SMALLINT,"
                "    F_TIME              TIME,"
                "    F_TIME_TZ           TIME WITH TIME ZONE,"
                "    F_TIMESHTAMP        TIMESTAMP,"
                "    F_TIMESHTAMP_TZ     TIMESTAMP WITH TIME ZONE,"
                "    F_VARCHAR           VARCHAR(64),"
                "    F_BLOB_B            BLOB SUB_TYPE BINARY,"
                "    F_BLOB_T            BLOB SUB_TYPE TEXT,"
                "    F_NULL              INTEGER"
                ")");
        } catch (...) {
            // Table already exists, ignore
        }

        // Try to insert test data (will fail if data with F_INTEGER=42 already exists due to UNIQUE constraint)
        try {
            conn->ExecuteDDL(
                "INSERT INTO TABLE_TEST_1 ("
                "    F_BIGINT, F_BOOLEAN, F_CHAR, F_DATE, F_DECFLOAT, F_DECIMAL, "
                "    F_DOUBLE_PRECISION, F_FLOAT, F_INT128, F_INTEGER, F_NUMERIC, "
                "    F_SMALINT, F_TIME, F_TIMESHTAMP, F_VARCHAR"
                ") VALUES ("
                "    9223372036854775807, TRUE, 'TEST', '2024-01-15', 123.456, 9876543.21, "
                "    3.14159265, 2.71828, 123456789012345678901234567890, 42, 123456.789, "
                "    32767, '12:34:56', '2024-01-15 12:34:56', 'Test String'"
                ")"
            );
        } catch (...) {
            // Data already exists (F_INTEGER=42 UNIQUE constraint), ignore
        }
    }

    static void TearDownTestSuite() {
        // Persistent database is not dropped
    }

    void SetUp() override {
        connection_ = std::make_unique<Connection>(db_params_);
    }

    void TearDown() override {
        connection_.reset();
    }

    std::unique_ptr<Connection> connection_;
    static ConnectionParams db_params_;
};

// Test with temporary database (recreated for each test)
class TempDatabaseTest : public FbppTestBase {
protected:
    void SetUp() override {
        // Use connection helper to get params with ENV overrides
        db_params_ = fbpp::util::getConnectionParams("tests.temp_db");

        // Add unique suffix to avoid conflicts
        auto pos = db_params_.database.rfind(".fdb");
        if (pos != std::string::npos) {
            db_params_.database.insert(pos, "_" + std::to_string(getCurrentProcessId()) +
                                           "_" + std::to_string(test_counter_++));
        }

        // Drop if exists and create new
        Connection::dropDatabase(db_params_);
        Connection::createDatabase(db_params_);

        connection_ = std::make_unique<Connection>(db_params_);

        // Create test schema
        createTestSchema();
    }

    void TearDown() override {
        connection_.reset();

        // Drop temporary database
        try {
            Connection::dropDatabase(db_params_);
        } catch (...) {
            // Ignore errors during cleanup
        }
    }

    virtual void createTestSchema() {
        connection_->ExecuteDDL(
            "CREATE TABLE test_table ("
            "    id INTEGER NOT NULL PRIMARY KEY,"
            "    name VARCHAR(100),"
            "    amount DOUBLE PRECISION"
            ")");
    }

    static long getCurrentProcessId() {
#if defined(_WIN32)
        return static_cast<long>(_getpid());
#else
        return static_cast<long>(getpid());
#endif
    }

    std::unique_ptr<Connection> connection_;
    ConnectionParams db_params_;
    static int test_counter_;
};


} // namespace test
} // namespace fbpp
