#include "test_base.hpp"

#include <algorithm>
#include <cctype>
#include <mutex>
#include <stdexcept>
#include <unordered_map>

namespace fbpp::test {
namespace {

struct SuiteDatabaseRegistry {
    std::mutex mutex;
    std::unordered_map<std::string, ConnectionParams> paramsBySuite;
};

SuiteDatabaseRegistry& suiteDatabaseRegistry() {
    static SuiteDatabaseRegistry registry;
    return registry;
}

std::string normalizeScope(std::string_view raw) {
    std::string normalized;
    normalized.reserve(raw.size());

    bool lastWasUnderscore = false;
    for (const char ch : raw) {
        const unsigned char uch = static_cast<unsigned char>(ch);
        if (std::isalnum(uch)) {
            normalized.push_back(static_cast<char>(std::tolower(uch)));
            lastWasUnderscore = false;
        } else if (!lastWasUnderscore) {
            normalized.push_back('_');
            lastWasUnderscore = true;
        }
    }

    while (!normalized.empty() && normalized.front() == '_') {
        normalized.erase(normalized.begin());
    }
    while (!normalized.empty() && normalized.back() == '_') {
        normalized.pop_back();
    }

    if (normalized.empty()) {
        normalized = "test_db";
    }

    return normalized;
}

long currentProcessId() {
#if defined(_WIN32)
    return static_cast<long>(_getpid());
#else
    return static_cast<long>(getpid());
#endif
}

std::string addScopeSuffix(std::string path, std::string_view scope) {
    const std::string suffix = "_" + normalizeScope(scope);
    const auto dotPos = path.find_last_of('.');
    if (dotPos != std::string::npos) {
        path.insert(dotPos, suffix);
        return path;
    }
    path += suffix;
    return path;
}

void executeDdlBatch(Connection& connection, std::initializer_list<const char*> statements) {
    for (const char* statement : statements) {
        connection.ExecuteDDL(statement);
    }
}

void applySchemaProfile(Connection& connection, const SchemaProfile profile) {
    switch (profile) {
        case SchemaProfile::BasicTable:
            executeDdlBatch(connection, {
                "CREATE TABLE test_table ("
                "    id INTEGER NOT NULL PRIMARY KEY,"
                "    name VARCHAR(100),"
                "    amount DOUBLE PRECISION"
                ")"
            });
            break;
        case SchemaProfile::QueryMetadata:
            executeDdlBatch(connection, {
                "CREATE TABLE test_data ("
                "    id INTEGER NOT NULL PRIMARY KEY,"
                "    name VARCHAR(100),"
                "    amount DOUBLE PRECISION,"
                "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                ")",
                "CREATE TABLE test_log ("
                "    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                "    message VARCHAR(500),"
                "    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                ")"
            });
            break;
        case SchemaProfile::TableTest1:
            executeDdlBatch(connection, {
                "CREATE TABLE TABLE_TEST_1 ("
                "    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                "    F_BIGINT            BIGINT,"
                "    F_BOOLEAN           BOOLEAN,"
                "    F_CHAR              CHAR(10),"
                "    F_DATE              DATE,"
                "    F_DECFLOAT          DECFLOAT(34),"
                "    F_DECIMAL           DECIMAL(34,8),"
                "    F_DOUBLE_PRECISION  DOUBLE PRECISION,"
                "    F_FLOAT             FLOAT,"
                "    F_INT128            INT128,"
                "    F_INTEGER           INTEGER,"
                "    F_NUMERIC           NUMERIC(16,6),"
                "    F_SMALINT           SMALLINT,"
                "    F_TIME              TIME,"
                "    F_TIME_TZ           TIME WITH TIME ZONE,"
                "    F_TIMESHTAMP        TIMESTAMP,"
                "    F_TIMESHTAMP_TZ     TIMESTAMP WITH TIME ZONE,"
                "    F_VARCHAR           VARCHAR(64),"
                "    F_BLOB_B            BLOB SUB_TYPE BINARY SEGMENT SIZE 1024,"
                "    F_BLOB_T            BLOB SUB_TYPE TEXT SEGMENT SIZE 1024,"
                "    F_NULL              INTEGER"
                ")",
                "ALTER TABLE TABLE_TEST_1 "
                "ADD CONSTRAINT UNQ1_TABLE_TEST_F_INTEGER UNIQUE (F_INTEGER)",
                "ALTER TABLE TABLE_TEST_1 "
                "ADD CONSTRAINT PK_TABLE_TEST_1 PRIMARY KEY (ID)"
            });
            break;
        case SchemaProfile::TTMath:
            executeDdlBatch(connection, {
                "CREATE TABLE TTMATH_TEST ("
                "    F_ID INTEGER NOT NULL PRIMARY KEY,"
                "    F_INT128_PURE INT128,"
                "    F_INT128_NULLABLE INT128,"
                "    F_NUMERIC38_2 NUMERIC(38, 2),"
                "    F_NUMERIC38_4 NUMERIC(38, 4),"
                "    F_NUMERIC38_8 NUMERIC(38, 8),"
                "    F_NUMERIC38_18 NUMERIC(38, 18),"
                "    F_NUMERIC18_2 NUMERIC(18, 2),"
                "    F_NUMERIC18_6 NUMERIC(18, 6),"
                "    F_NAME VARCHAR(100)"
                ")"
            });
            break;
        case SchemaProfile::DecFloat:
            executeDdlBatch(connection, {
                "CREATE TABLE DECFLOAT_TEST ("
                "    F_ID INTEGER NOT NULL PRIMARY KEY,"
                "    F_DECFLOAT16 DECFLOAT(16),"
                "    F_DECFLOAT16_NULLABLE DECFLOAT(16),"
                "    F_DECFLOAT34 DECFLOAT(34),"
                "    F_DECFLOAT34_NULLABLE DECFLOAT(34),"
                "    F_NAME VARCHAR(100)"
                ")"
            });
            break;
        case SchemaProfile::DateTime:
            executeDdlBatch(connection, {
                "CREATE TABLE DATETIME_TEST ("
                "    F_ID INTEGER NOT NULL PRIMARY KEY,"
                "    F_DATE DATE,"
                "    F_DATE_NULLABLE DATE,"
                "    F_TIME TIME,"
                "    F_TIMESTAMP TIMESTAMP,"
                "    F_TIMESTAMP_NULLABLE TIMESTAMP,"
                "    F_NAME VARCHAR(100)"
                ")"
            });
            break;
        case SchemaProfile::Combined:
            executeDdlBatch(connection, {
                "CREATE TABLE COMBINED_TEST ("
                "    F_ID INTEGER NOT NULL PRIMARY KEY,"
                "    F_INT128 INT128,"
                "    F_NUMERIC38_2 NUMERIC(38, 2),"
                "    F_DECFLOAT16 DECFLOAT(16),"
                "    F_DECFLOAT34 DECFLOAT(34),"
                "    F_DATE DATE,"
                "    F_TIMESTAMP TIMESTAMP,"
                "    F_NAME VARCHAR(100)"
                ")"
            });
            break;
        case SchemaProfile::ExtendedTypes:
            executeDdlBatch(connection, {
                "CREATE TABLE TEST_EXTENDED_TYPES ("
                "    ID INTEGER NOT NULL PRIMARY KEY,"
                "    VAL_INT128 INT128,"
                "    VAL_DEC16 DECFLOAT(16),"
                "    VAL_DEC34 DECFLOAT(34),"
                "    VAL_TIMESTAMP TIMESTAMP,"
                "    VAL_TIMESTAMP_TZ TIMESTAMP WITH TIME ZONE,"
                "    VAL_TIME TIME,"
                "    VAL_TIME_TZ TIME WITH TIME ZONE,"
                "    VAL_DATE DATE,"
                "    VAL_NUMERIC_SCALE NUMERIC(18, 4)"
                ")"
            });
            break;
    }
}

std::string buildSuiteScope(const ::testing::TestInfo* testInfo) {
    return std::string(testInfo->test_suite_name()) + "_" +
           std::to_string(currentProcessId());
}

std::string buildTestScope(const ::testing::TestInfo* testInfo, const int counter) {
    return std::string(testInfo->test_suite_name()) + "_" +
           testInfo->name() + "_" +
           std::to_string(currentProcessId()) + "_" +
           std::to_string(counter);
}

} // namespace

ConnectionParams makeScopedTestDatabaseParams(std::string_view scope,
                                              std::string_view section) {
    ConnectionParams params = fbpp::util::getConnectionParams(std::string(section));

    const auto separator = params.database.find(':');
    if (separator == std::string::npos) {
        params.database = addScopeSuffix(params.database, scope);
        return params;
    }

    const std::string prefix = params.database.substr(0, separator);
    const std::string path = params.database.substr(separator + 1);
    params.database = prefix + ":" + addScopeSuffix(path, scope);
    return params;
}

void recreateTestDatabase(const ConnectionParams& params) {
    Connection::dropDatabase(params);
    Connection::createDatabase(params);
}

void dropTestDatabaseQuietly(const ConnectionParams& params) noexcept {
    try {
        Connection::dropDatabase(params);
    } catch (...) {
        // Best-effort cleanup only.
    }
}

void applySchemaProfiles(Connection& connection, const std::vector<SchemaProfile>& profiles) {
    for (const auto profile : profiles) {
        applySchemaProfile(connection, profile);
    }
}

void ManagedDatabaseTest::initializeDatabase() {
    if (!connection_) {
        throw std::runtime_error("ManagedDatabaseTest requires an active connection");
    }

    applySchemaProfiles(*connection_, schemaProfiles());
    createTestSchema();
    seedTestData();
}

void SuiteDatabaseTest::SetUp() {
    const auto* testInfo = ::testing::UnitTest::GetInstance()->current_test_info();
    if (!testInfo) {
        throw std::runtime_error("Unable to resolve current test info");
    }

    auto& registry = suiteDatabaseRegistry();
    {
        std::lock_guard<std::mutex> lock(registry.mutex);
        auto it = registry.paramsBySuite.find(testInfo->test_suite_name());
        if (it == registry.paramsBySuite.end()) {
            ConnectionParams params = makeScopedTestDatabaseParams(buildSuiteScope(testInfo));
            recreateTestDatabase(params);

            try {
                db_params_ = params;
                connection_ = std::make_unique<Connection>(db_params_);
                initializeDatabase();
                connection_.reset();
            } catch (...) {
                connection_.reset();
                dropTestDatabaseQuietly(params);
                throw;
            }

            it = registry.paramsBySuite.emplace(testInfo->test_suite_name(), params).first;
        }

        db_params_ = it->second;
    }

    connection_ = std::make_unique<Connection>(db_params_);
}

void SuiteDatabaseTest::TearDownTestSuite() {
    const auto* suite = ::testing::UnitTest::GetInstance()->current_test_suite();
    if (!suite) {
        return;
    }

    auto& registry = suiteDatabaseRegistry();
    ConnectionParams params;
    bool found = false;
    {
        std::lock_guard<std::mutex> lock(registry.mutex);
        auto it = registry.paramsBySuite.find(suite->name());
        if (it != registry.paramsBySuite.end()) {
            params = it->second;
            registry.paramsBySuite.erase(it);
            found = true;
        }
    }

    if (found) {
        dropTestDatabaseQuietly(params);
    }
}

void SuiteDatabaseTest::TearDown() {
    connection_.reset();
}

void TempDatabaseTest::SetUp() {
    const auto* testInfo = ::testing::UnitTest::GetInstance()->current_test_info();
    if (!testInfo) {
        throw std::runtime_error("Unable to resolve current test info");
    }

    db_params_ = makeScopedTestDatabaseParams(buildTestScope(testInfo, test_counter_++));
    recreateTestDatabase(db_params_);
    connection_ = std::make_unique<Connection>(db_params_);
    initializeDatabase();
}

void TempDatabaseTest::TearDown() {
    connection_.reset();
    dropTestDatabaseQuietly(db_params_);
}

void TempDatabaseTest::createTestSchema() {
    applySchemaProfiles(*connection_, {SchemaProfile::BasicTable});
}

int TempDatabaseTest::test_counter_ = 0;

} // namespace fbpp::test
