-- Unified schema for persistent databases used by fbpp tests and query_generator.
-- Ensures required tables exist; existing schemas remain untouched.

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'TABLE_TEST_1')) THEN
        EXECUTE STATEMENT '
            CREATE TABLE TABLE_TEST_1 (
                ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                F_BIGINT            BIGINT,
                F_BOOLEAN           BOOLEAN,
                F_CHAR              CHAR(10),
                F_DATE              DATE,
                F_DECFLOAT          DECFLOAT(34),
                F_DECIMAL           DECIMAL(34,8),
                F_DOUBLE_PRECISION  DOUBLE PRECISION,
                F_FLOAT             FLOAT,
                F_INT128            INT128,
                F_INTEGER           INTEGER UNIQUE,
                F_NUMERIC           NUMERIC(16,6),
                F_SMALINT           SMALLINT,
                F_TIME              TIME,
                F_TIME_TZ           TIME WITH TIME ZONE,
                F_TIMESHTAMP        TIMESTAMP,
                F_TIMESHTAMP_TZ     TIMESTAMP WITH TIME ZONE,
                F_VARCHAR           VARCHAR(64),
                F_BLOB_B            BLOB SUB_TYPE BINARY,
                F_BLOB_T            BLOB SUB_TYPE TEXT,
                F_NULL              INTEGER
            )
        ';
END^

EXECUTE BLOCK AS
BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'TTMATH_TEST')) THEN
        EXECUTE STATEMENT '
            CREATE TABLE TTMATH_TEST (
                F_ID INTEGER NOT NULL PRIMARY KEY,
                F_INT128_PURE INT128,
                F_INT128_NULLABLE INT128,
                F_NUMERIC38_2 NUMERIC(38, 2),
                F_NUMERIC38_4 NUMERIC(38, 4),
                F_NUMERIC38_8 NUMERIC(38, 8),
                F_NUMERIC38_18 NUMERIC(38, 18),
                F_NUMERIC18_2 NUMERIC(18, 2),
                F_NUMERIC18_6 NUMERIC(18, 6),
                F_NAME VARCHAR(100)
            )
        ';
END^

EXECUTE BLOCK AS
BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'DECFLOAT_TEST')) THEN
        EXECUTE STATEMENT '
            CREATE TABLE DECFLOAT_TEST (
                F_ID INTEGER NOT NULL PRIMARY KEY,
                F_DECFLOAT16 DECFLOAT(16),
                F_DECFLOAT16_NULLABLE DECFLOAT(16),
                F_DECFLOAT34 DECFLOAT(34),
                F_DECFLOAT34_NULLABLE DECFLOAT(34),
                F_NAME VARCHAR(100)
            )
        ';
END^

EXECUTE BLOCK AS
BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'DATETIME_TEST')) THEN
        EXECUTE STATEMENT '
            CREATE TABLE DATETIME_TEST (
                F_ID INTEGER NOT NULL PRIMARY KEY,
                F_DATE DATE,
                F_DATE_NULLABLE DATE,
                F_TIME TIME,
                F_TIMESTAMP TIMESTAMP,
                F_TIMESTAMP_NULLABLE TIMESTAMP,
                F_NAME VARCHAR(100)
            )
        ';
END^

EXECUTE BLOCK AS
BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'COMBINED_TEST')) THEN
        EXECUTE STATEMENT '
            CREATE TABLE COMBINED_TEST (
                F_ID INTEGER NOT NULL PRIMARY KEY,
                F_INT128 INT128,
                F_NUMERIC38_2 NUMERIC(38, 2),
                F_DECFLOAT16 DECFLOAT(16),
                F_DECFLOAT34 DECFLOAT(34),
                F_DATE DATE,
                F_TIMESTAMP TIMESTAMP,
                F_NAME VARCHAR(100)
            )
        ';
END^

SET TERM ; ^

UPDATE OR INSERT INTO TABLE_TEST_1 (
    F_BIGINT, F_BOOLEAN, F_CHAR, F_DATE, F_DECFLOAT, F_DECIMAL,
    F_DOUBLE_PRECISION, F_FLOAT, F_INT128, F_INTEGER, F_NUMERIC,
    F_SMALINT, F_TIME, F_TIMESHTAMP, F_VARCHAR
) VALUES (
    9223372036854775807, TRUE, 'TEST', '2024-01-15', 123.456, 9876543.21,
    3.14159265, 2.71828, 123456789012345678901234567890, 42, 123456.789,
    32767, '12:34:56', '2024-01-15 12:34:56', 'Test String'
)
MATCHING (F_INTEGER);

COMMIT;
